name: firebase_testlab_detector
description: This Flutter plugin for Android determines whether the app is running within Firebase Test Lab, which is used for Google Play Pre-Launch Reports.
repository: https://github.com/nohli/firebase_testlab_detector
issue_tracker: https://github.com/nohli/firebase_testlab_detector/issues

version: 0.0.1

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.achim.firebase_testlab_detector
        pluginClass: FirebaseTestlabDetectorPlugin
